name: PHP Composer CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Validate composer.json and composer.lock
    - name: Validate Composer Files
      run: composer validate --strict

    # Cache Composer dependencies
    - name: Cache Composer Dependencies
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # Install Composer dependencies
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    # Run PHPUnit test suite
    - name: Run Test Suite
      run: |
        if [ -f "vendor/bin/phpunit" ]; then
          vendor/bin/phpunit --configuration phpunit.xml.dist
        else
          echo "PHPUnit is not installed. Skipping tests."
        fi

    # Lint PHP files for syntax errors
    - name: Lint PHP Files
      run: find . -name "*.php" -exec php -l {} \;

    # Security check using Composer
    - name: Run Composer Security Audit
      run: composer audit --locked
